version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: teamconnect-postgres
    environment:
      POSTGRES_DB: teamconnect
      POSTGRES_USER: teamconnect
      POSTGRES_PASSWORD: teamconnect123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teamconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teamconnect"]
      interval: 10s
      timeout: 5s
      retries: 5

  couchbase:
    build:
      context: .
      dockerfile: Dockerfile.couchbase
    container_name: teamconnect-couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var
    networks:
      - teamconnect-network
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=root
      - COUCHBASE_ADMINISTRATOR_PASSWORD=plplpl123
    command: bash -c "/entrypoint.sh couchbase-server & sleep 15 && /opt/couchbase/init/couchbase-init.sh && wait"

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "teamconnect_cookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - teamconnect-network

networks:
  teamconnect-network:
    driver: bridge

volumes:
  postgres_data:
    name: teamconnect_postgres_data
    driver: local
  couchbase_data:
    name: teamconnect_couchbase_data
    driver: local
  rabbitmq_data:
    name: teamconnect_rabbitmq_data
    driver: local
